### ISSUE TITLE
生成了6000个数据来做SFT，跑了3个epoch，没记住训练集

### ISSUE THREAD

**Issue by TccccD** [ziliwangnlp/RefGPT#3]
生成了6000个数据来做全量参数的SFT，没用lora等，跑了3个epochs，没记住训练集，回答的结果和训练集基本不相干。想请教下，你们在做SFT的时候，是跑了很多epoch吗。
@ziliwangnlp

**Comment by mutonix** [comment]
这应该是数据处理出了点问题
