### ISSUE TITLE
询问方法的更多细节，请问你们何时能公开论文？

### ISSUE THREAD

**Issue by Luffyzm3D2Y** [ziliwangnlp/RefGPT#5]
你好，我对你们的研究很感兴趣，想知道你们方法的更多细节，比如prompt的构造、数据集的构造，以及方法的其他更多细节。请问你们会发表论文吗？预计什么时候会不会先在arXiv上公开一版？

**Comment by Luffyzm3D2Y** [comment]
或者能不能给我推荐一篇使用LLM构造对话指令集的论文，我在搜索调研相关工作，感谢🙏

**Comment by mutonix** [comment]
我们已经公开了论文  近期会公开数据
